# Generated by Django 5.2.9 on 2025-12-03 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('horario_inicio', models.TimeField(default='09:00:00')),
                ('horario_fin', models.TimeField(default='18:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Duracion estimada del servicio en minutos.')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(blank=True, editable=False, null=True)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='RESERVADO', max_length=10)),
                ('codigo_reserva', models.CharField(editable=False, max_length=32, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app_turnos.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='app_turnos.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_turnos.servicio')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
    ]
